import TheBirth
import datetime
# print(TheBirth.whoOld(14))
# # print(TheBirth.theYoungest())
# print(TheBirth.whozodiac("Scorpio"))
# print(TheBirth.iszodiac("Kankrai"))
# print(TheBirth.theOldest(), TheBirth.theYoungest())
# print(TheBirth.time_lived("aedr"))
# print(TheBirth.isInC12("Kankrai"))
# print(TheBirth.countdowntobirth("kank"))
# a = TheBirth.countdowntobirth("kan")
# print(TheBirth.iszodiac("mangkorn"))
# print(TheBirth.whozodiac("Aries"))
# print(TheBirth.nearestBirthDay())
# print(datetime.datetime(2006,4,24).weekday())
# print(TheBirth.whoBornIn(date=22,weekday=6))
# print(datetime.datetime(2022, 2, 6).weekday())
# print(TheBirth.whoBornIn(month="Mar"))
# print(TheBirth.countdowntobirth(""))
# print(TheBirth.checkDate(50))
# print(TheBirth.whoBornIn(year=2006, month="apr", day=22, weekday="sat"))
print(TheBirth.whoBornIn(day=17, weekday="wed"))